# Site wide configuration

title: LOOK MA! 
description: Every new line has a purpose
logo: # 120x120 px default image used for Twitter summary card
teaser: default.png # 400x250 px default teaser image used in image archive grid
locale:
url: http://munk801.github.io
# url: http://localhost:4000

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
plugins:
  - jekyll-sitemap


# Site owner
owner:
  name: Stephen Lu
  email: munk801@gmail.com
  twitter: StephenMunkLu
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname:

About: '/about'
Archive: '/archive'

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
